"""initial schema

Revision ID: 0000
Revises: 
Create Date: 2026-04-03 21:37:59.874486
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '0000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('imported_stats_daily',
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('input_token', sa.Integer(), nullable=False),
    sa.Column('output_token', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('wait_time', sa.Integer(), nullable=False),
    sa.Column('request_success', sa.Integer(), nullable=False),
    sa.Column('request_failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('imported_stats_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_token', sa.Integer(), nullable=False),
    sa.Column('output_token', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('wait_time', sa.Integer(), nullable=False),
    sa.Column('request_success', sa.Integer(), nullable=False),
    sa.Column('request_failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_group_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=False),
    sa.Column('channel_id', sa.String(length=80), nullable=False),
    sa.Column('credential_id', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_group_items_channel_id'), 'model_group_items', ['channel_id'], unique=False)
    op.create_index(op.f('ix_model_group_items_credential_id'), 'model_group_items', ['credential_id'], unique=False)
    op.create_index(op.f('ix_model_group_items_group_id'), 'model_group_items', ['group_id'], unique=False)
    op.create_table('model_groups',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=40), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('match_regex', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_groups_name'), 'model_groups', ['name'], unique=False)
    op.create_index(op.f('ix_model_groups_protocol'), 'model_groups', ['protocol'], unique=False)
    op.create_table('model_prices',
    sa.Column('model_key', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('input_price_per_million', sa.Float(), nullable=False),
    sa.Column('output_price_per_million', sa.Float(), nullable=False),
    sa.Column('cache_read_price_per_million', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('cache_write_price_per_million', sa.Float(), nullable=False, server_default='0.0'),
    sa.PrimaryKeyConstraint('model_key')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.String(length=40), nullable=False),
    sa.Column('requested_model', sa.String(length=200), nullable=True),
    sa.Column('matched_group_name', sa.String(length=120), nullable=True),
    sa.Column('channel_id', sa.String(length=80), nullable=True),
    sa.Column('gateway_key_id', sa.String(length=80), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('resolved_model', sa.String(length=200), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost_usd', sa.Float(), nullable=False),
    sa.Column('output_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_channel_id'), 'request_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_gateway_key_id'), 'request_logs', ['gateway_key_id'], unique=False)
    op.create_index(op.f('ix_request_logs_protocol'), 'request_logs', ['protocol'], unique=False)
    op.create_index(op.f('ix_request_logs_resolved_model'), 'request_logs', ['resolved_model'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('site_credentials',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_credentials_site_id'), 'site_credentials', ['site_id'], unique=False)
    op.create_table('site_discovered_models',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('protocol_config_id', sa.String(length=80), nullable=False),
    sa.Column('credential_id', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_discovered_models_credential_id'), 'site_discovered_models', ['credential_id'], unique=False)
    op.create_index(op.f('ix_site_discovered_models_protocol_config_id'), 'site_discovered_models', ['protocol_config_id'], unique=False)
    op.create_table('site_protocol_configs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('site_id', sa.String(length=80), nullable=False),
    sa.Column('protocol', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('headers_json', sa.Text(), nullable=False),
    sa.Column('channel_proxy', sa.Text(), nullable=False),
    sa.Column('param_override', sa.Text(), nullable=False),
    sa.Column('match_regex', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_protocol_configs_protocol'), 'site_protocol_configs', ['protocol'], unique=False)
    op.create_index(op.f('ix_site_protocol_configs_site_id'), 'site_protocol_configs', ['site_id'], unique=False)
    op.create_table('site_protocol_credential_bindings',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('protocol_config_id', sa.String(length=80), nullable=False),
    sa.Column('credential_id', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_protocol_credential_bindings_credential_id'), 'site_protocol_credential_bindings', ['credential_id'], unique=False)
    op.create_index(op.f('ix_site_protocol_credential_bindings_protocol_config_id'), 'site_protocol_credential_bindings', ['protocol_config_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_site_protocol_credential_bindings_protocol_config_id'), table_name='site_protocol_credential_bindings')
    op.drop_index(op.f('ix_site_protocol_credential_bindings_credential_id'), table_name='site_protocol_credential_bindings')
    op.drop_table('site_protocol_credential_bindings')
    op.drop_index(op.f('ix_site_protocol_configs_site_id'), table_name='site_protocol_configs')
    op.drop_index(op.f('ix_site_protocol_configs_protocol'), table_name='site_protocol_configs')
    op.drop_table('site_protocol_configs')
    op.drop_index(op.f('ix_site_discovered_models_protocol_config_id'), table_name='site_discovered_models')
    op.drop_index(op.f('ix_site_discovered_models_credential_id'), table_name='site_discovered_models')
    op.drop_table('site_discovered_models')
    op.drop_index(op.f('ix_site_credentials_site_id'), table_name='site_credentials')
    op.drop_table('site_credentials')
    op.drop_table('settings')
    op.drop_index(op.f('ix_request_logs_resolved_model'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_protocol'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_gateway_key_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_channel_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_table('model_prices')
    op.drop_index(op.f('ix_model_groups_protocol'), table_name='model_groups')
    op.drop_index(op.f('ix_model_groups_name'), table_name='model_groups')
    op.drop_table('model_groups')
    op.drop_index(op.f('ix_model_group_items_group_id'), table_name='model_group_items')
    op.drop_index(op.f('ix_model_group_items_credential_id'), table_name='model_group_items')
    op.drop_index(op.f('ix_model_group_items_channel_id'), table_name='model_group_items')
    op.drop_table('model_group_items')
    op.drop_table('imported_stats_total')
    op.drop_table('imported_stats_daily')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
