"""trim model group fields

Revision ID: 30364ceff335
Revises: 0000
Create Date: 2026-04-04 21:52:58.175577
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '30364ceff335'
down_revision = '0000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_group_items', 'channel_name_snapshot')
    op.drop_column('model_group_items', 'credential_name_snapshot')
    op.drop_column('model_groups', 'session_keep_time')
    op.drop_column('model_groups', 'first_token_timeout')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups', sa.Column('first_token_timeout', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('model_groups', sa.Column('session_keep_time', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('model_group_items', sa.Column('credential_name_snapshot', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False))
    op.add_column('model_group_items', sa.Column('channel_name_snapshot', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False))
    # ### end Alembic commands ###

